### PR TITLE
Improvement of some levels and new `UnlockForUnlock`, `FindBall` and `BlockUnlockPickup` levels

### PR DESCRIPTION
**Pull request by lcswillems**

### CODE REVIEW

**Comment by maximecb** [comment]
In the future, please make smaller PRs more often, as opposed to massive PRs with tens of commits.

Why did you change FindObj to FindBall?

**Comment by lcswillems** [comment]
Okay, I see, but I did all this yesterday night. I just added FindBall, FindObj is still here. FindBall is an easier version of FindObj to remove all the difficulties except the memory.

**Comment by lcswillems** [comment]
Ooh I see. There are a lot of commits here. I don't understand why again... The commits of the days before yesterday are already in master...

**Comment by maximecb** [comment]
To avoid that problem, do `git checkout -b newbranch` and create a PR from that branch.

You can also cherry-pick commits from your branch into the new branch with `git cherry-pick <commit_hash>`.

**Pull request merged**
