### PR TITLE
Fixed several bugs

### PR DESCRIPTION
**Pull request by lcswillems**

### CODE REVIEW

**Comment by maximecb** [comment]
Doesn't need to be a specific object type for`PickupAbove`

**Comment by lcswillems** [comment]
I didn't force the object in PickupAbove to be a key. It is in HiddenKeyCorridor. 

image

The lines goes from 401 to 626. It took me some time also to realize there was some code between.

**Comment by maximecb** [comment]
That display is confusing, but same remark for `HiddenKeyCorridor`. You could add an "obj_type" field to the constructor if you want to force a specific object type for your experiments, but leave the difficulty of the level unchanged.

**Comment by lcswillems** [comment]
Maybe I could add this to all the levels of this kind?

**Comment by maximecb** [comment]
I would only add it if you think it's useful for solving that level, because [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).

**Comment by lcswillems** [comment]
Yes, sure. I didn't mean to set a specific object for all the levels. I mean: for all the levels I think it is useful to set a specific object, would you like I add it to the constructor? Because, it is not the case actually.

**Comment by maximecb** [comment]
I don't think it's useful to add this functionality to every level that has some specific objects. Just add it to this one, or add it when you actually need it.

**Comment by saleml** [comment]
For some levels it's necessary to specify the objects in the environment. Example, if the agent is cornered by objects they're not supposed to pick, they are stuck (e.g. https://i.imgur.com/8xUrV9i.png). For this example, I think it makes sense to force the distractors to be boxed (so that they can be opened), as other objects would have to be picked and then thrown, which will make the agent lose...

**Comment by maximecb** [comment]
@saleml Two things:

- I think a more ideal fix for that would be to make it so distractors can never corner the agent. 

- The probability of this happening seems very small. I expect it wouldn't stop the agent from learning.

**Comment by lcswillems** [comment]
I reverted the commit "Removed early stopping that can cause impossible environments". You are right, it will not stop the learning because it is really unlikely. Finding a better placement of the distractors would be a better fix but it is quite hard because there is not only the case when the agent is blocked in a corner that is problematic. It can be blocked in the center also. For the moment, we can just keep it how it is.

I also added `obj_type` to the parameter of the constructor.

**Pull request merged**
